[package]
name = "chat_program"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "chat_server"
path = "src/server.rs"

[[bin]]
name = "chat_client"
path = "src/client.rs"
[dependencies]
